# Generated by Django 5.2.17 on 2026-10-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("esports", "0001_initial"),
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matchday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                (
                    "descrizione",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data", models.DateField(blank=True, null=True)),
                ("chiusa", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            (
                                "WAITING_FOR_POSTPONED_MATCHES",
                                "Waiting For Postponed Matches",
                            ),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=40,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("provisional", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchdays",
                        to="leagues.league",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="competitions.stage",
                    ),
                ),
            ],
            options={
                "db_table": "matchdays",
                "ordering": ["league_id", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("CARRIED", "Carried"),
                            ("AUTOMATIC", "Automatic"),
                            ("MISSING", "Missing"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("punteggio_totale", models.FloatField(blank=True, null=True)),
                ("bench_order", models.JSONField(blank=True, default=list)),
                ("effective_titolari", models.JSONField(blank=True, default=list)),
                ("captain_points", models.FloatField(blank=True, null=True)),
                ("penalty_points", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capitano",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="esports.proplayer",
                    ),
                ),
                (
                    "fanta_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to="leagues.fantateam",
                    ),
                ),
                (
                    "titolari",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="esports.proplayer"
                    ),
                ),
                (
                    "vice_capitano",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="esports.proplayer",
                    ),
                ),
                (
                    "matchday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to="matchdays.matchday",
                    ),
                ),
            ],
            options={
                "db_table": "formations",
            },
        ),
        migrations.CreateModel(
            name="PlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.PositiveIntegerField(default=0)),
                ("morti", models.PositiveIntegerField(default=0)),
                ("assist", models.PositiveIntegerField(default=0)),
                ("cs", models.PositiveIntegerField(default=0)),
                ("vision_score", models.PositiveIntegerField(default=0)),
                ("vittoria", models.BooleanField(default=False)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("games_played", models.PositiveIntegerField(default=1)),
                ("series_played", models.PositiveIntegerField(default=1)),
                (
                    "formula_version",
                    models.CharField(
                        choices=[
                            ("HISTORICAL", "Formula storica"),
                            ("REGIONAL_V1", "Regionale v1"),
                            ("SUMMER_2026_V1", "Summer 2026 v1 (alias di REGIONAL_V1)"),
                        ],
                        default="REGIONAL_V1",
                        max_length=32,
                    ),
                ),
                ("fantavoto", models.FloatField()),
                (
                    "source",
                    models.CharField(
                        choices=[("AUTO", "Auto"), ("MANUAL", "Manual")],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                ("complete", models.BooleanField(default=True)),
                (
                    "matchday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistiche",
                        to="matchdays.matchday",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="esports.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "player_stats",
            },
        ),
        migrations.AddConstraint(
            model_name="matchday",
            constraint=models.UniqueConstraint(
                fields=("league", "numero"), name="uniq_matchday_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="formation",
            constraint=models.UniqueConstraint(
                fields=("fanta_team", "matchday"), name="uniq_formation"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerstat",
            constraint=models.UniqueConstraint(
                fields=("matchday", "player"), name="uniq_player_stat"
            ),
        ),
    ]
