# Generated by Django 5.1.15 on 2026-09-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("PARTIAL", "PARTIAL"),
                            ("ERROR", "ERROR"),
                            ("SKIPPED", "SKIPPED"),
                        ],
                        default="OK",
                        max_length=20,
                    ),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("inserted", models.IntegerField(default=0)),
                ("updated", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ingest_sync_states",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pandascore_id", models.BigIntegerField(unique=True)),
                ("slug", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("league_code", models.CharField(db_index=True, max_length=20)),
                ("league_pandascore_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "tournament_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("serie_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "not_started"),
                            ("running", "running"),
                            ("finished", "finished"),
                            ("canceled", "canceled"),
                            ("postponed", "postponed"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "begin_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("number_of_games", models.IntegerField(default=0)),
                ("opponents", models.JSONField(blank=True, default=list)),
                ("results", models.JSONField(blank=True, default=list)),
                (
                    "winner_name",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("leaguepedia_checked_at", models.DateTimeField(blank=True, null=True)),
                ("leaguepedia_synced_at", models.DateTimeField(blank=True, null=True)),
                ("leaguepedia_attempts", models.IntegerField(default=0)),
                (
                    "leaguepedia_error",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "worlds_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="worlds.worldsstage",
                    ),
                ),
            ],
            options={
                "db_table": "ingest_matches",
                "ordering": ["-begin_at"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_number", models.IntegerField(default=1)),
                ("external_game_id", models.CharField(db_index=True, max_length=200)),
                ("played_at", models.DateTimeField(db_index=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("patch", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "winner_name",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("mvp_link", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "mvp_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mvp_games",
                        to="teams.proplayer",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="ingest.match",
                    ),
                ),
            ],
            options={
                "db_table": "ingest_games",
                "ordering": ["played_at", "game_number"],
            },
        ),
        migrations.CreateModel(
            name="PlayerAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=160, unique=True)),
                ("canonical_name", models.CharField(max_length=160)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to="teams.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "ingest_player_aliases",
                "ordering": ["source_name"],
            },
        ),
        migrations.CreateModel(
            name="TeamAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=160, unique=True)),
                ("canonical_name", models.CharField(max_length=160)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to="teams.proteam",
                    ),
                ),
            ],
            options={
                "db_table": "ingest_team_aliases",
                "ordering": ["source_name"],
            },
        ),
        migrations.CreateModel(
            name="GamePlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_link", models.CharField(max_length=160)),
                (
                    "source_team_name",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TOP", "TOP"),
                            ("JUNGLE", "JUNGLE"),
                            ("MID", "MID"),
                            ("ADC", "ADC"),
                            ("SUPPORT", "SUPPORT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("champion", models.CharField(blank=True, max_length=80, null=True)),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("cs", models.IntegerField(default=0)),
                ("gold", models.IntegerField(default=0)),
                ("damage", models.IntegerField(default=0)),
                ("vision_score", models.IntegerField(default=0)),
                ("win", models.BooleanField(default=False)),
                ("fantasy_score", models.FloatField(default=0.0)),
                ("corrected_kills", models.IntegerField(blank=True, null=True)),
                ("corrected_deaths", models.IntegerField(blank=True, null=True)),
                ("corrected_assists", models.IntegerField(blank=True, null=True)),
                ("corrected_cs", models.IntegerField(blank=True, null=True)),
                ("corrected_vision_score", models.IntegerField(blank=True, null=True)),
                ("corrected_win", models.BooleanField(blank=True, null=True)),
                ("corrected_participated", models.BooleanField(blank=True, null=True)),
                ("overridden", models.BooleanField(default=False)),
                (
                    "override_actor",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="ingest.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_stats",
                        to="teams.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "ingest_game_player_stats",
                "indexes": [
                    models.Index(
                        fields=["player", "game"], name="ingest_game_player__29d5b3_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "player"), name="uq_game_player_stat"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["status", "leaguepedia_synced_at", "leaguepedia_checked_at"],
                name="idx_match_enrich_queue",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["league_code", "begin_at"], name="idx_match_league_begin"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("external_game_id",), name="uq_game_external_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("match", "game_number"), name="uq_game_match_number"
            ),
        ),
    ]
