# Generated by Django 5.2.17 on 2026-10-05 15:15

import apps.leagues.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("esports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FantaTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("crediti_residui", models.IntegerField()),
                ("punti", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fanta_teams",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "codice_invito",
                    models.CharField(
                        default=apps.leagues.models._invite_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("crediti_iniziali", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("auction_open", models.BooleanField(default=False)),
                (
                    "participant_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ruleset",
                    models.CharField(
                        choices=[("REGIONAL", "Regionale"), ("WORLDS", "Worlds")],
                        default="REGIONAL",
                        max_length=16,
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "leagues",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crediti_spesi", models.PositiveIntegerField()),
                ("data_acquisto", models.DateTimeField(auto_now_add=True)),
                ("exclusive", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "roster_entries",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AuctionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_bid", models.PositiveIntegerField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("WON", "Won"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="esports.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "auction_sessions",
            },
        ),
    ]
