# Generated by Django 5.2.17 on 2026-10-05 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("esports", "0001_initial"),
        ("leagues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fantateam",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fanta_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionsession",
            name="highest_bidder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leagues.fantateam",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_leagues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leagues",
                to="competitions.competitionedition",
            ),
        ),
        migrations.AddField(
            model_name="fantateam",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fanta_teams",
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="auctionsession",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auctions",
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="fanta_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosa",
                to="leagues.fantateam",
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roster_entries",
                to="esports.proplayer",
            ),
        ),
        migrations.AddConstraint(
            model_name="fantateam",
            constraint=models.UniqueConstraint(
                fields=("league", "owner"), name="uniq_team_owner_league"
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("league",),
                name="uniq_active_auction_per_league",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterentry",
            constraint=models.UniqueConstraint(
                fields=("fanta_team", "player"), name="uniq_roster_team_player"
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exclusive", True)),
                fields=("league", "player"),
                name="uniq_exclusive_player_league",
            ),
        ),
    ]
