# Generated by Django 5.1.15 on 2026-09-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingest", "0001_initial"),
        ("leagues", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matchday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                (
                    "descrizione",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data", models.DateField(blank=True, null=True)),
                ("chiusa", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            (
                                "WAITING_FOR_POSTPONED_MATCHES",
                                "WAITING_FOR_POSTPONED_MATCHES",
                            ),
                            ("CLOSED", "CLOSED"),
                        ],
                        default="OPEN",
                        max_length=40,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchdays",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "db_table": "matchdays",
                "ordering": ["league_id", "numero"],
            },
        ),
        migrations.CreateModel(
            name="ImportedGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="ingest.game",
                    ),
                ),
                (
                    "matchday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_games",
                        to="matchdays.matchday",
                    ),
                ),
            ],
            options={
                "db_table": "imported_games",
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "SUBMITTED"),
                            ("CARRIED", "CARRIED"),
                            ("AUTOMATIC", "AUTOMATIC"),
                            ("MISSING", "MISSING"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("punteggio_totale", models.FloatField(blank=True, null=True)),
                (
                    "fanta_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formazioni",
                        to="leagues.fantateam",
                    ),
                ),
                (
                    "titolari",
                    models.ManyToManyField(
                        db_table="formation_titolari",
                        related_name="formazioni",
                        to="teams.proplayer",
                    ),
                ),
                (
                    "matchday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formazioni",
                        to="matchdays.matchday",
                    ),
                ),
            ],
            options={
                "db_table": "formations",
            },
        ),
        migrations.CreateModel(
            name="PlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.IntegerField(default=0)),
                ("morti", models.IntegerField(default=0)),
                ("assist", models.IntegerField(default=0)),
                ("cs", models.IntegerField(default=0)),
                ("vision_score", models.IntegerField(default=0)),
                ("vittoria", models.BooleanField(default=False)),
                ("wins", models.IntegerField(default=0)),
                ("games_played", models.IntegerField(default=1)),
                ("fantavoto", models.FloatField(default=0.0)),
                (
                    "matchday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistiche",
                        to="matchdays.matchday",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchday_stats",
                        to="teams.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "player_stats",
            },
        ),
        migrations.AddConstraint(
            model_name="matchday",
            constraint=models.UniqueConstraint(
                fields=("league", "numero"), name="uq_matchday_league_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="importedgame",
            constraint=models.UniqueConstraint(
                fields=("game", "matchday"), name="uq_imported_game_matchday"
            ),
        ),
        migrations.AddConstraint(
            model_name="formation",
            constraint=models.UniqueConstraint(
                fields=("fanta_team", "matchday"), name="uq_formation_team_matchday"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerstat",
            constraint=models.UniqueConstraint(
                fields=("matchday", "player"), name="uq_playerstat_matchday_player"
            ),
        ),
    ]
