# Generated by Django 5.2.17 on 2026-10-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("esports", "0001_initial"),
        ("leagues", "0001_initial"),
        ("matchdays", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_out", models.PositiveIntegerField(default=0)),
                ("price_in", models.PositiveIntegerField(default=0)),
                ("is_free", models.BooleanField(default=True)),
                ("freed_by_elimination", models.BooleanField(default=False)),
                ("penalty_points", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fanta_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="leagues.fantateam",
                    ),
                ),
                (
                    "matchday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="matchdays.matchday",
                    ),
                ),
                (
                    "player_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="esports.proplayer",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="esports.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "worlds_transfers",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
