from django.urls import path

from .views import (
    EditionDetailView,
    EditionListView,
    EditionPoolView,
    EditionStagesView,
    EditionSyncPoolView,
    StageImportMatchesView,
    WorldsAuctionBidView,
    WorldsLeagueAuctionView,
    WorldsLeagueDetailView,
    WorldsLeagueJoinView,
    WorldsLeagueListView,
    WorldsLeagueTeamsView,
    WorldsLineupView,
    WorldsRecomputeView,
    WorldsStandingsView,
    WorldsSwapView,
    WorldsTeamRosterCompleteView,
)

urlpatterns = [
    path("editions/", EditionListView.as_view(), name="worlds-editions"),
    path("editions/<int:edition_id>/", EditionDetailView.as_view(), name="worlds-edition"),
    path("editions/<int:edition_id>/stages/", EditionStagesView.as_view(), name="worlds-stages"),
    path("editions/<int:edition_id>/pool/", EditionPoolView.as_view(), name="worlds-pool"),
    path("editions/<int:edition_id>/sync-pool/", EditionSyncPoolView.as_view(),
         name="worlds-sync-pool"),
    path("stages/<int:stage_id>/import-matches/", StageImportMatchesView.as_view(),
         name="worlds-stage-import"),
    path("leagues/", WorldsLeagueListView.as_view(), name="worlds-leagues"),
    path("leagues/join/", WorldsLeagueJoinView.as_view(), name="worlds-league-join"),
    path("leagues/<int:league_id>/", WorldsLeagueDetailView.as_view(), name="worlds-league"),
    path("leagues/<int:league_id>/teams/", WorldsLeagueTeamsView.as_view(), name="worlds-teams"),
    path("leagues/<int:league_id>/auction/", WorldsLeagueAuctionView.as_view(),
         name="worlds-auction"),
    path("leagues/<int:league_id>/auction/<str:state>/", WorldsLeagueAuctionView.as_view(),
         name="worlds-auction-state"),
    path("auctions/<int:auction_id>/bids/", WorldsAuctionBidView.as_view(), name="worlds-bid"),
    path("teams/<int:team_id>/roster/complete/", WorldsTeamRosterCompleteView.as_view(),
         name="worlds-roster-complete"),
    path("leagues/<int:league_id>/swap/", WorldsSwapView.as_view(), name="worlds-swap"),
    path("leagues/<int:league_id>/lineup/", WorldsLineupView.as_view(), name="worlds-lineup"),
    path("leagues/<int:league_id>/standings/", WorldsStandingsView.as_view(),
         name="worlds-standings"),
    path("leagues/<int:league_id>/recompute/", WorldsRecomputeView.as_view(),
         name="worlds-recompute"),
]
