const state={token:localStorage.getItem('fantalol_token'),user:JSON.parse(localStorage.getItem('fantalol_user')||'null'),leagueId:null,league:null,leagueTeams:[],mine:[],activeTeam:null,players:[],teams:[],matchdays:[],activeAuction:null,auctionTimer:null,auctionRefreshPending:false,occupied:new Set(),activeSection:'overview'};
const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const roles=['TOP','JUNGLE','MID','ADC','SUPPORT'];

async function api(path,options={}){const headers={'Content-Type':'application/json',...options.headers,Authorization:`Bearer ${state.token}`};const response=await fetch(`/api${path}`,{...options,headers});if(response.status===204)return null;const data=await response.json().catch(()=>null);if(!response.ok){if(response.status===401){logout(false);return null}const details=data?.details?.join(' · ');throw new Error(details||data?.message||`Errore HTTP ${response.status}`)}return data}
function toast(message,error=false){const element=$('#toast');element.textContent=message;element.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.className='toast',3200)}
function logout(notify=true){localStorage.removeItem('fantalol_token');localStorage.removeItem('fantalol_user');if(notify)location.href='/index.html?login=1#leagues';else location.replace('/index.html?login=1#leagues')}
function canManageLeague(){return state.user?.role==='ADMIN'||state.league?.adminUsername===state.user?.username}
function rosterLimit(){return state.league?.maxRosterSize??(state.league?.numeroSquadre<=5?10:5)}
function showError(message){$('#league-loading').classList.add('hidden');$('#league-dashboard').classList.add('hidden');$('#league-error-message').textContent=message;$('#league-error').classList.remove('hidden')}

async function initialise(){
    if(!state.token||!state.user){location.replace('/index.html?login=1#leagues');return}
    $('#user-chip').textContent=`${state.user.username} · ${state.user.role}`;
    state.leagueId=LeagueUtils.parseLeagueId(location.search);
    if(!state.leagueId){showError('Il link della lega non contiene un identificativo valido.');return}
    try{
        const leagues=await api('/leagues');if(!leagues)return;
        state.league=leagues.find(league=>Number(league.id)===state.leagueId);
        if(!state.league){showError('Questa lega non esiste oppure non è accessibile dal tuo account.');return}
        const [leagueTeams,mine,players,teams,matchdays]=await Promise.all([api(`/fanta-teams/by-league/${state.leagueId}`),api('/fanta-teams/me'),api('/players'),api('/teams'),api('/matchdays')]);
        if(!leagueTeams||!mine||!players||!teams||!matchdays)return;
        state.leagueTeams=leagueTeams;state.mine=mine;state.players=players;state.teams=teams;state.matchdays=matchdays.filter(day=>Number(day.leagueId)===state.leagueId);state.activeTeam=mine.find(team=>Number(team.leagueId)===state.leagueId)||null;
        renderDashboard();await renderExternalData();
        $('#league-loading').classList.add('hidden');$('#league-dashboard').classList.remove('hidden');
    }catch(error){showError(error.message)}
}

function renderDashboard(){
    document.title=`${state.league.nome} — FantaLeague`;$('#league-name').textContent=state.league.nome;$('#league-admin').textContent=`Admin · ${state.league.adminUsername}`;$('#league-code').textContent=state.league.codiceInvito;$('#overview-title').textContent=state.league.nome;
    const auctionState=$('#auction-state');auctionState.textContent=state.league.auctionOpen?'Asta aperta':'Asta chiusa';auctionState.classList.toggle('open',state.league.auctionOpen);
    $('#league-metrics').innerHTML=`<article class="metric-card"><span>Fantasy team</span><strong>${state.leagueTeams.length}</strong></article><article class="metric-card"><span>Crediti iniziali</span><strong>${state.league.creditiIniziali}</strong></article><article class="metric-card"><span>Giornate</span><strong>${state.matchdays.length}</strong></article>`;
    renderRanking();renderTeams();renderMatchdays();renderAuction();
}
function renderRanking(){const ranked=LeagueUtils.rankFantasyTeams(state.leagueTeams);$('#fantasy-ranking').innerHTML=ranked.length?ranked.map((team,index)=>`<div class="ranking-row"><span class="rank">${String(index+1).padStart(2,'0')}</span><span class="ranking-team"><strong>${escapeHtml(team.nome)}</strong><small>${escapeHtml(team.ownerUsername||'Manager')}</small></span><strong class="ranking-points">${team.punti} pt</strong></div>`).join(''):'<p class="empty-list">Nessun fantasy team iscritto.</p>'}
function renderTeams(){$('#league-teams').innerHTML=state.leagueTeams.length?state.leagueTeams.map(team=>{const roster=[...(team.rosa||[])].sort((left,right)=>roles.indexOf(left.ruolo)-roles.indexOf(right.ruolo)||left.lecPlayerNickname.localeCompare(right.lecPlayerNickname,'it'));return `<article class="league-team-card"><div class="team-card-head"><div><p>${escapeHtml(team.ownerUsername||'Manager')}</p><h3>${escapeHtml(team.nome)}</h3><p>${team.creditiResidui} crediti rimasti</p></div><strong class="team-points">${Number(team.punti??0).toFixed(1)} pt</strong></div>${roster.length?`<div class="roster-list">${roster.map(player=>`<div class="roster-player"><span class="role">${escapeHtml(player.ruolo)}</span><strong>${escapeHtml(player.lecPlayerNickname)}</strong><small>${player.creditiSpesi} cr</small></div>`).join('')}</div>`:'<p class="empty-roster">Rosa ancora vuota</p>'}</article>`}).join(''):'<p class="empty-list">Nessun fantasy team iscritto.</p>'}
function renderMatchdays(){const manager=canManageLeague();const participant=Boolean(state.activeTeam)||manager;$('#create-matchday-button').classList.toggle('hidden',!manager||state.matchdays.some(day=>!day.chiusa));const rosterButton=$('#open-formation-button');rosterButton.textContent=state.league.maxPerRole===1?'Vedi la tua rosa':'Modifica formazione';rosterButton.classList.toggle('hidden',!state.activeTeam||state.activeTeam.rosa.length<5||!state.matchdays.length||state.league.auctionOpen);$('#matchdays-list').innerHTML=state.matchdays.length?[...state.matchdays].sort((a,b)=>b.numero-a.numero).map(day=>{const dataStatus=day.scoringStatus==='COMPLETE'?'Punteggio completo':day.scoringStatus==='CONFLICT'?'Conflitto statistiche':day.scoringStatus==='EMPTY'?'In attesa dei dati':'Punteggio provvisorio';const formationStatus=day.formationLocked?'Formazioni bloccate':day.auctionLocked?'In attesa della chiusura asta':'Formazioni aperte';return `<article class="matchday-card"><div><h3>Giornata ${day.numero}</h3><p>${escapeHtml(day.descrizione||'Giornata di lega')}${day.data?` · ${escapeHtml(day.data)}`:''}</p><small>${formationStatus}${day.formationLockedBy?` · ${escapeHtml(day.formationLockedBy)}`:''}</small></div><div class="matchday-actions"><span class="day-status ${day.scoringStatus==='CONFLICT'?'conflict':''}">${dataStatus}</span>${participant?`<button class="button button-ghost" data-formation-lock="${day.id}" data-locked="${day.formationLocked}">${day.formationLocked?'Sblocca':'Blocca'} formazioni</button>`:''}</div></article>`}).join(''):'<div class="integration-state"><span class="integration-icon">◇</span><h3>Nessuna giornata</h3><p>Il calendario Summer non è ancora stato sincronizzato.</p></div>'}
async function renderExternalData(){const [standings,performances]=await Promise.all([LecDataSource.loadStandings(),LecDataSource.loadPlayerPerformances()]);if(standings.status==='not-connected')renderIntegrationState('#lec-standings','Classifica LEC in arrivo','Collega qui la fonte ufficiale della competizione per visualizzare posizioni, vittorie e sconfitte.');if(performances.status==='not-connected')renderIntegrationState('#player-performance','Performance in arrivo','Collega qui la fonte ufficiale per analizzare tutte le prestazioni dei player durante il torneo LEC.')}
function renderIntegrationState(selector,title,copy){$(selector).innerHTML=`<span class="integration-icon">⌁</span><h3>${title}</h3><p>${copy}</p><span class="integration-label">Fonte ufficiale non collegata</span>`}

function setSection(section){state.activeSection=section;$$('[data-view]').forEach(view=>view.classList.toggle('hidden',view.dataset.view!==section));$$('[data-section]').forEach(button=>{const active=button.dataset.section===section;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});if(section==='auction')startAuctionPolling();else stopAuctionPolling()}
function startAuctionPolling(){refreshAuction();stopAuctionPolling();state.auctionTimer=setInterval(refreshAuction,500)}
function stopAuctionPolling(){clearInterval(state.auctionTimer);state.auctionTimer=null}
async function refreshAuction(){if(state.auctionRefreshPending)return;state.auctionRefreshPending=true;try{const [leagueTeams,auction,leagues]=await Promise.all([api(`/fanta-teams/by-league/${state.leagueId}`),api(`/auctions/active?leagueId=${state.leagueId}`),api('/leagues')]);if(!leagueTeams||!leagues)return;state.leagueTeams=leagueTeams;state.activeAuction=auction;state.league=leagues.find(league=>Number(league.id)===state.leagueId)||state.league;state.activeTeam=leagueTeams.find(team=>team.id===state.activeTeam?.id)||state.activeTeam;state.occupied=new Set(leagueTeams.flatMap(team=>team.rosa||[]).map(entry=>entry.lecPlayerId));renderAuction();renderMatchdays();renderTeams();renderRanking()}catch(error){toast(error.message,true)}finally{state.auctionRefreshPending=false}}
function renderAuction(){const team=state.activeTeam;const auction=state.activeAuction;const manager=canManageLeague();const open=state.league.auctionOpen;$('#auction-phase-controls').innerHTML=`<span class="auction-phase-${open?'open':'closed'}">${open?'Asta aperta':'Asta chiusa'}</span>${manager?`<button class="button ${open?'button-danger':'button-primary'}" data-auction-phase="${open?'close':'open'}">${open?'Termina asta':'Avvia asta'}</button>`:''}`;$('#auto-complete-button').classList.toggle('hidden',open||!manager||!team);if(!team){$('#auction-summary').innerHTML='<strong>Modalità spettatore</strong><span>Entra nella lega con il codice invito per partecipare.</span>';$('#auction-list').innerHTML='<p class="auction-wait">Puoi seguire lo stato dell’asta, ma non effettuare operazioni.</p>';return}const seconds=auction?Math.max(0,(new Date(auction.endsAt)-Date.now())/1000):0;const nextMinimum=auction?auction.currentBid+1:0;const canAfford=!auction||team.creditiResidui>=nextMinimum;$('#auction-summary').innerHTML=auction?`<div class="live-auction"><span class="live-dot"></span><strong>${escapeHtml(auction.playerNickname)}</strong><span>Offerta: <b>${auction.currentBid}</b></span><span>Leader: <b>${escapeHtml(auction.highestBidderName||'—')}</b></span><span class="countdown">${seconds.toFixed(1)}s</span>${open?`<form data-bid="${auction.id}"><input type="number" name="credits" min="${nextMinimum}" value="${nextMinimum}" max="${team.creditiResidui}" ${canAfford?'':'disabled'}><button class="button button-primary" ${canAfford?'':'disabled'}>Rilancia</button>${canAfford?'':'<p class="bid-unavailable">Non hai abbastanza crediti per rilanciare</p>'}</form>`:''}</div>`:`<strong>${escapeHtml(team.nome)}</strong><span>${team.creditiResidui} crediti disponibili</span><span>${team.rosa.length}/${rosterLimit()} player</span>`;if(!open){$('#auction-list').innerHTML='<p class="auction-wait">Il creatore della lega deve avviare l’asta per consentire nomine e rilanci.</p>';return}$('#auction-list').innerHTML=auction?'<p class="auction-wait">Ogni rilancio riavvia il timer a 10 secondi; allo scadere il player va al miglior offerente.</p>':state.players.map(player=>{const mine=team.rosa.find(entry=>entry.lecPlayerId===player.id);const taken=state.occupied.has(player.id)&&!mine;return `<article class="auction-row ${taken?'taken':''}"><div><span class="role">${escapeHtml(player.ruolo)}</span><strong>${escapeHtml(player.nickname)}</strong><small>${escapeHtml(player.teamNome)} · base ${player.quotazione}</small></div>${mine?`<button class="button button-ghost" data-release="${mine.id}">Rilascia</button>`:taken?'<span class="sold">ASSEGNATO</span>':`<button class="button button-primary" data-start-auction="${player.id}" ${team.rosa.length>=rosterLimit()||team.creditiResidui<player.quotazione?'disabled':''}>Avvia asta · ${player.quotazione}</button>`}</article>`}).join('')}

async function openFormation(){if(!state.activeTeam||state.league.auctionOpen){toast('Termina l’asta prima di usare la rosa.',true);return}const history=await api(`/fanta-teams/${state.activeTeam.id}/formazioni`);const days=[...state.matchdays].sort((a,b)=>b.numero-a.numero);const openDays=days.filter(day=>!day.chiusa&&!day.auctionLocked);const selectable=openDays.length?openDays:days.slice(0,1);$('#formation-form [name=matchdayId]').innerHTML=selectable.map(day=>`<option value="${day.id}">Giornata ${day.numero} · ${escapeHtml(day.descrizione||'')}</option>`).join('');const editable=state.league.maxPerRole===2&&openDays.length>0;const lastFormation=[...(history||[])].reverse().find(item=>item.source!=='MISSING');const selectedByRole=new Map((lastFormation?.players||[]).map(player=>[player.role,String(player.id)]));$('#formation-status').textContent=editable?'Scegli un player per ogni ruolo. Se non salvi, resta valida l’ultima formazione.':'La formazione coincide automaticamente con i cinque player della tua rosa.';$('#formation-roles').innerHTML=roles.map(role=>{const players=state.activeTeam.rosa.filter(entry=>entry.ruolo===role);if(!editable){const player=players[0];return `<article class="formation-role-card"><span>${role}</span><strong>${escapeHtml(player?.lecPlayerNickname||'Non assegnato')}</strong></article>`}return `<label>${role}<select name="role-${role}" required><option value="">Seleziona</option>${players.map(player=>`<option value="${player.lecPlayerId}" ${selectedByRole.get(role)===String(player.lecPlayerId)?'selected':''}>${escapeHtml(player.lecPlayerNickname)}</option>`).join('')}</select></label>`}).join('');$('#formation-form button[type=submit]').classList.toggle('hidden',!editable);$('#roster-history').innerHTML=renderRosterHistory(history||[]);$('#formation-dialog').showModal()}
function renderRosterHistory(history){if(!history.length)return '<p class="empty-roster">Nessun risultato disponibile.</p>';return `<h3>PUNTI PER GIORNATA</h3>${history.map(item=>{const day=state.matchdays.find(entry=>entry.id===item.matchdayId);return `<article class="history-day"><header><strong>Giornata ${day?.numero??''}</strong><span>${Number(item.punteggioTotale??0).toFixed(1)} pt medi</span></header>${(item.players||[]).map(player=>`<div><span>${escapeHtml(player.role)}</span><strong>${escapeHtml(player.nickname)}</strong><b class="${player.matchdayScore<0?'negative':''}">${Number(player.matchdayScore??0).toFixed(1)} pt</b></div>`).join('')||'<p>Prima formazione non inserita: 0 pt</p>'}</article>`}).join('')}`}
function openMatchday(){const form=$('#matchday-form');form.reset();form.elements.leagueId.value=state.leagueId;$('.form-error',form).textContent='';$('#matchday-dialog').showModal()}

$('#league-navigation').addEventListener('click',event=>{const button=event.target.closest('[data-section]');if(button)setSection(button.dataset.section)});
$('#matchdays-list').addEventListener('click',async event=>{const button=event.target.closest('[data-formation-lock]');if(!button)return;try{const locked=button.dataset.locked==='true';const updated=await api(`/matchdays/${button.dataset.formationLock}/formation-lock`,{method:locked?'DELETE':'POST'});state.matchdays=state.matchdays.map(day=>day.id===updated.id?updated:day);renderMatchdays();toast(locked?'Formazioni sbloccate':'Formazioni bloccate')}catch(error){toast(error.message,true)}});
$('#logout-button').addEventListener('click',()=>logout());$('#create-matchday-button').addEventListener('click',openMatchday);$('#open-formation-button').addEventListener('click',()=>openFormation().catch(error=>toast(error.message,true)));
$$('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
$('#auction-list').addEventListener('click',async event=>{const start=event.target.closest('[data-start-auction]');const release=event.target.closest('[data-release]');try{if(start)state.activeAuction=await api('/auctions',{method:'POST',body:JSON.stringify({leagueId:state.leagueId,lecPlayerId:Number(start.dataset.startAuction),fantaTeamId:state.activeTeam.id})});if(release){await api(`/fanta-teams/${state.activeTeam.id}/rosa/${release.dataset.release}`,{method:'DELETE'});toast('Player rilasciato: rimborso del 50%')}await refreshAuction()}catch(error){toast(error.message,true)}});
$('#auction-summary').addEventListener('submit',async event=>{const form=event.target.closest('[data-bid]');if(!form)return;event.preventDefault();try{state.activeAuction=await api(`/auctions/${form.dataset.bid}/bids`,{method:'POST',body:JSON.stringify({fantaTeamId:state.activeTeam.id,credits:Number(new FormData(form).get('credits'))})});renderAuction()}catch(error){toast(error.message,true)}});
$('#auction-phase-controls').addEventListener('click',async event=>{const button=event.target.closest('[data-auction-phase]');if(!button)return;try{const action=button.dataset.auctionPhase;await api(`/leagues/${state.leagueId}/auction/${action}`,{method:'PUT'});await refreshAuction();toast(action==='open'?'Asta della lega avviata':'Asta della lega terminata')}catch(error){toast(error.message,true)}});
$('#auto-complete-button').addEventListener('click',async()=>{try{await api(`/leagues/${state.leagueId}/rosters/complete-randomly`,{method:'POST'});toast('Rose completate casualmente rispettando i ruoli');await refreshAuction();renderTeams();renderRanking()}catch(error){toast(error.message,true)}});
$('#formation-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));const titolariIds=roles.map(role=>Number(values[`role-${role}`]));try{await api(`/fanta-teams/${state.activeTeam.id}/formazioni`,{method:'PUT',body:JSON.stringify({matchdayId:Number(values.matchdayId),titolariIds})});$('#formation-dialog').close();toast('Formazione schierata correttamente')}catch(error){$('.form-error',form).textContent=error.message}});
$('#matchday-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));try{const day=await api('/matchdays',{method:'POST',body:JSON.stringify({leagueId:state.leagueId,numero:Number(values.numero),descrizione:values.descrizione,data:values.data||null})});state.matchdays.push(day);state.league.auctionOpen=true;$('#matchday-dialog').close();renderMatchdays();renderAuction();toast(`Giornata ${day.numero} creata: asta aperta`)}catch(error){$('.form-error',form).textContent=error.message}});
window.addEventListener('beforeunload',stopAuctionPolling);initialise();
