# Generated by Django 5.2.17 on 2026-10-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pandascore_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "leaguepedia_link",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                ("nickname", models.CharField(max_length=60)),
                ("real_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "nationality",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("image_url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "image_file",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("image_hash", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pro_players",
                "ordering": ["nickname"],
            },
        ),
        migrations.CreateModel(
            name="ProTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pandascore_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=120)),
                ("acronym", models.CharField(blank=True, default="", max_length=20)),
                ("slug", models.SlugField(blank=True, default="", max_length=140)),
                ("location", models.CharField(blank=True, default="", max_length=60)),
                (
                    "image_url_light",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "image_url_dark",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("logo_file", models.CharField(blank=True, default="", max_length=255)),
                ("logo_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "leaguepedia_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pro_teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EsportsMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pandascore_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("canceled", "Canceled"),
                            ("postponed", "Postponed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("begin_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("number_of_games", models.PositiveSmallIntegerField(default=1)),
                (
                    "pandascore_tournament_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("pandascore_serie_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "tournament_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("leaguepedia_synced_at", models.DateTimeField(blank=True, null=True)),
                ("leaguepedia_checked_at", models.DateTimeField(blank=True, null=True)),
                ("stats_complete", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="competitions.competitionedition",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="competitions.stage",
                    ),
                ),
                (
                    "winner_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="esports.proteam",
                    ),
                ),
            ],
            options={
                "db_table": "esports_matches",
                "ordering": ["begin_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EsportsGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_number", models.PositiveSmallIntegerField()),
                (
                    "leaguepedia_game_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("length_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                ("mvp_link", models.CharField(blank=True, default="", max_length=160)),
                (
                    "overview_page",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="esports.esportsmatch",
                    ),
                ),
                (
                    "winner_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="esports.proteam",
                    ),
                ),
            ],
            options={
                "db_table": "esports_games",
                "ordering": ["match_id", "game_number"],
            },
        ),
        migrations.CreateModel(
            name="PlayerAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leaguepedia_link", models.CharField(max_length=160, unique=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="esports.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "player_aliases",
            },
        ),
        migrations.CreateModel(
            name="EditionRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TOP", "Top"),
                            ("JUNGLE", "Jungle"),
                            ("MID", "Mid"),
                            ("ADC", "ADC"),
                            ("SUPPORT", "Support"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quotazione", models.PositiveIntegerField(default=1)),
                ("quotazione_set_by_admin", models.BooleanField(default=False)),
                ("is_starter", models.BooleanField(default=True)),
                ("in_listone", models.BooleanField(blank=True, null=True)),
                ("active_from", models.DateTimeField()),
                ("active_to", models.DateTimeField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="competitions.competitionedition",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edition_rosters",
                        to="esports.proplayer",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edition_rosters",
                        to="esports.proteam",
                    ),
                ),
            ],
            options={
                "db_table": "edition_rosters",
                "ordering": ["edition_id", "team__name", "role"],
            },
        ),
        migrations.CreateModel(
            name="ProviderSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("PANDASCORE", "Pandascore"),
                            ("LEAGUEPEDIA", "Leaguepedia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="AWAITING_DATA", max_length=20)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("sync_requested_at", models.DateTimeField(blank=True, null=True)),
                ("inserted_games", models.PositiveIntegerField(default=0)),
                ("updated_games", models.PositiveIntegerField(default=0)),
                ("skipped_games", models.PositiveIntegerField(default=0)),
                ("failed_games", models.PositiveIntegerField(default=0)),
                ("unmatched_players", models.JSONField(blank=True, default=list)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_states",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "db_table": "provider_sync_states",
            },
        ),
        migrations.CreateModel(
            name="TeamAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pandascore_name", models.CharField(max_length=120, unique=True)),
                ("leaguepedia_name", models.CharField(max_length=120)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="esports.proteam",
                    ),
                ),
            ],
            options={
                "db_table": "team_aliases",
            },
        ),
        migrations.CreateModel(
            name="GamePlayerStatOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participated", models.BooleanField(blank=True, null=True)),
                ("kills", models.IntegerField(blank=True, null=True)),
                ("deaths", models.IntegerField(blank=True, null=True)),
                ("assists", models.IntegerField(blank=True, null=True)),
                ("cs", models.IntegerField(blank=True, null=True)),
                ("vision_score", models.IntegerField(blank=True, null=True)),
                ("win", models.BooleanField(blank=True, null=True)),
                ("champion", models.CharField(blank=True, default="", max_length=60)),
                ("actor", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="esports.esportsgame",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_overrides",
                        to="esports.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "game_player_stat_overrides",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "player"), name="uniq_override_game_player"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GamePlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leaguepedia_link", models.CharField(max_length=160)),
                (
                    "source_team_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("side", models.CharField(blank=True, default="", max_length=10)),
                ("role", models.CharField(blank=True, default="", max_length=10)),
                ("champion", models.CharField(blank=True, default="", max_length=60)),
                ("kills", models.IntegerField(blank=True, null=True)),
                ("deaths", models.IntegerField(blank=True, null=True)),
                ("assists", models.IntegerField(blank=True, null=True)),
                ("gold", models.IntegerField(blank=True, null=True)),
                ("cs", models.IntegerField(blank=True, null=True)),
                ("damage_to_champions", models.IntegerField(blank=True, null=True)),
                ("vision_score", models.IntegerField(blank=True, null=True)),
                ("win", models.BooleanField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("LEAGUEPEDIA", "Leaguepedia"), ("MANUAL", "Manual")],
                        default="LEAGUEPEDIA",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="esports.esportsgame",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_stats",
                        to="esports.proplayer",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="esports.proteam",
                    ),
                ),
            ],
            options={
                "db_table": "game_player_stats",
                "ordering": ["game_id", "id"],
                "indexes": [models.Index(fields=["player"], name="idx_stat_player")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "leaguepedia_link"),
                        name="uniq_game_player_link",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EsportsMatchTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=1)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("winner", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_teams",
                        to="esports.esportsmatch",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_entries",
                        to="esports.proteam",
                    ),
                ),
            ],
            options={
                "db_table": "esports_match_teams",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "team"), name="uniq_match_team"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="esportsmatch",
            index=models.Index(
                models.OrderBy(models.F("leaguepedia_checked_at"), nulls_first=True),
                models.OrderBy(models.F("end_at"), descending=True),
                condition=models.Q(
                    ("leaguepedia_synced_at__isnull", True), ("status", "finished")
                ),
                name="idx_match_enrich_queue",
            ),
        ),
        migrations.AddIndex(
            model_name="esportsmatch",
            index=models.Index(
                fields=["edition", "begin_at"], name="idx_match_edition_begin"
            ),
        ),
        migrations.AddConstraint(
            model_name="esportsgame",
            constraint=models.UniqueConstraint(
                fields=("match", "game_number"), name="uniq_game_number"
            ),
        ),
        migrations.AddIndex(
            model_name="editionroster",
            index=models.Index(
                fields=["edition", "active_to"], name="idx_roster_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="editionroster",
            constraint=models.UniqueConstraint(
                fields=("edition", "player", "active_from"), name="uniq_roster_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="providersyncstate",
            constraint=models.UniqueConstraint(
                fields=("provider", "competition"), name="uniq_provider_competition"
            ),
        ),
        migrations.AddConstraint(
            model_name="providersyncstate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("competition__isnull", True)),
                fields=("provider",),
                name="uniq_provider_global",
            ),
        ),
    ]
