# Generated by Django 5.2.17 on 2026-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proplayer",
            name="image_etag",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="proteam",
            name="logo_etag",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
