# Generated by Django 5.2.17 on 2026-10-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("esports", "0001_initial"),
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EffectiveLineupPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TOP", "Top"),
                            ("JUNGLE", "Jungle"),
                            ("MID", "Mid"),
                            ("ADC", "ADC"),
                            ("SUPPORT", "Support"),
                        ],
                        max_length=10,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("AUTOMATIC", "Automatic"),
                            ("BACKFILL", "Backfill"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fanta_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_periods",
                        to="leagues.fantateam",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="esports.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "effective_lineup_periods",
                "ordering": ["fanta_team_id", "effective_from"],
                "indexes": [
                    models.Index(
                        fields=["fanta_team", "role", "effective_from"],
                        name="idx_lineup_period_active",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fanta_team", "role", "effective_from"),
                        name="uniq_lineup_period",
                    )
                ],
            },
        ),
    ]
