# Generated by Django 5.2.17 on 2026-10-05 15:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("region", models.CharField(max_length=60)),
                (
                    "ruleset",
                    models.CharField(
                        choices=[("REGIONAL", "Regionale"), ("WORLDS", "Worlds")],
                        default="REGIONAL",
                        max_length=16,
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Rome", max_length=64)),
                (
                    "pandascore_league_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "leaguepedia_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("logo", models.CharField(blank=True, default="", max_length=255)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "competitions",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="LineupPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("FIXED_WEEKLY_WINDOW", "Finestra settimanale fissa"),
                            (
                                "LOCK_BEFORE_FIRST_MATCH",
                                "Blocco prima della prima serie",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("open_day", models.PositiveSmallIntegerField(default=2)),
                ("close_day", models.PositiveSmallIntegerField(default=4)),
                ("effective_day", models.PositiveSmallIntegerField(default=5)),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                ("lock_minutes", models.PositiveIntegerField(default=60)),
            ],
            options={
                "db_table": "lineup_policies",
            },
        ),
        migrations.CreateModel(
            name="CompetitionEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("pandascore_serie_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "pandascore_tournament_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "leaguepedia_overview_pages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scoring_formula_version",
                    models.CharField(
                        choices=[
                            ("HISTORICAL", "Formula storica"),
                            ("REGIONAL_V1", "Regionale v1"),
                            ("SUMMER_2026_V1", "Summer 2026 v1 (alias di REGIONAL_V1)"),
                        ],
                        default="REGIONAL_V1",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("listone_published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editions",
                        to="competitions.competition",
                    ),
                ),
                (
                    "lineup_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="competitions.lineuppolicy",
                    ),
                ),
            ],
            options={
                "db_table": "competition_editions",
                "ordering": ["competition__display_order", "-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PLAY_IN", "Play-In"),
                            ("SWISS", "Swiss Stage"),
                            ("QUARTERFINALS", "Quarti di finale"),
                            ("SEMIFINALS", "Semifinali"),
                            ("FINAL", "Finale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_players_per_team",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("free_transfers_unlimited_before", models.BooleanField(default=False)),
                ("budget_bonus", models.IntegerField(default=0)),
                (
                    "pandascore_tournament_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="competitions.competitionedition",
                    ),
                ),
            ],
            options={
                "db_table": "stages",
                "ordering": ["edition_id", "order"],
            },
        ),
        migrations.AddConstraint(
            model_name="competitionedition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pandascore_serie_id__isnull", False)),
                fields=("pandascore_serie_id",),
                name="uniq_edition_pandascore_serie",
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("edition", "code"), name="uniq_stage_code"
            ),
        ),
    ]
