# Generated by Django 5.1.15 on 2026-09-17 15:28

import django.db.models.deletion
import worlds.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldsEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("anno", models.PositiveIntegerField()),
                (
                    "pandascore_tournament_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("default_crediti", models.PositiveIntegerField(default=500)),
                ("default_roster_size", models.PositiveIntegerField(default=10)),
                ("default_max_per_role", models.PositiveIntegerField(default=2)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qualified_teams",
                    models.ManyToManyField(
                        blank=True, related_name="worlds_editions", to="teams.proteam"
                    ),
                ),
            ],
            options={
                "db_table": "worlds_editions",
                "ordering": ["-anno", "nome"],
            },
        ),
        migrations.CreateModel(
            name="WorldsLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "codice_invito",
                    models.CharField(
                        default=worlds.models.generate_invite_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("crediti_iniziali", models.PositiveIntegerField()),
                ("roster_size", models.PositiveIntegerField()),
                ("max_per_role", models.PositiveIntegerField()),
                ("auction_open", models.BooleanField(default=False)),
                ("allow_reentry_swap", models.BooleanField(default=True)),
                ("mvp_bonus", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worlds_leghe_amministrate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leagues",
                        to="worlds.worldsedition",
                    ),
                ),
            ],
            options={
                "db_table": "worlds_leagues",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WorldsStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("ordine", models.PositiveIntegerField()),
                (
                    "pandascore_tournament_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("lineup_deadline", models.DateTimeField(blank=True, null=True)),
                ("lineups_locked", models.BooleanField(default=False)),
                ("advancement_bonus", models.FloatField(default=0.0)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="worlds.worldsedition",
                    ),
                ),
            ],
            options={
                "db_table": "worlds_stages",
                "ordering": ["edition_id", "ordine"],
            },
        ),
        migrations.CreateModel(
            name="WorldsTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("crediti_residui", models.IntegerField()),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="worlds.worldsleague",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worlds_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "worlds_teams",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WorldsStageLineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("punteggio", models.FloatField(default=0.0)),
                ("bonus", models.FloatField(default=0.0)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="worlds.worldsstage",
                    ),
                ),
                (
                    "titolari",
                    models.ManyToManyField(
                        db_table="worlds_stage_lineup_titolari",
                        related_name="worlds_lineups",
                        to="teams.proplayer",
                    ),
                ),
                (
                    "fanta_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="worlds.worldsteam",
                    ),
                ),
            ],
            options={
                "db_table": "worlds_stage_lineups",
            },
        ),
        migrations.CreateModel(
            name="WorldsRosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crediti_spesi", models.PositiveIntegerField(default=0)),
                ("data_acquisto", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worlds_roster_entries",
                        to="teams.proplayer",
                    ),
                ),
                (
                    "acquired_from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="worlds.worldsstage",
                    ),
                ),
                (
                    "released_at_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="worlds.worldsstage",
                    ),
                ),
                (
                    "fanta_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosa",
                        to="worlds.worldsteam",
                    ),
                ),
            ],
            options={
                "db_table": "worlds_roster_entries",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WorldsAuctionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_bid", models.PositiveIntegerField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("WON", "WON"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worlds_auctions",
                        to="teams.proplayer",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to="worlds.worldsleague",
                    ),
                ),
                (
                    "highest_bidder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auctions_won",
                        to="worlds.worldsteam",
                    ),
                ),
            ],
            options={
                "db_table": "worlds_auction_sessions",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="worldsstage",
            constraint=models.UniqueConstraint(
                fields=("edition", "ordine"), name="uq_worlds_stage_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="worldsteam",
            constraint=models.UniqueConstraint(
                fields=("league", "owner"), name="uq_worlds_team_league_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="worldsstagelineup",
            constraint=models.UniqueConstraint(
                fields=("fanta_team", "stage"), name="uq_worlds_lineup_team_stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="worldsrosterentry",
            constraint=models.UniqueConstraint(
                fields=("fanta_team", "player"), name="uq_worlds_roster_team_player"
            ),
        ),
        migrations.AddIndex(
            model_name="worldsauctionsession",
            index=models.Index(
                fields=["status", "ends_at"], name="worlds_auct_status_bf343c_idx"
            ),
        ),
    ]
