# Generated by Django 5.1.15 on 2026-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldsleague",
            name="series_win_bonus",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="worldsleague",
            name="mvp_bonus",
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name="worldsstage",
            name="advancement_bonus",
            field=models.FloatField(default=2.0),
        ),
    ]
