# Generated by Django 5.1.15 on 2026-09-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("sigla", models.CharField(blank=True, max_length=10, null=True)),
                ("logo_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "competition",
                    models.CharField(
                        choices=[
                            ("LEC", "LEC"),
                            ("LPL", "LPL"),
                            ("LCK", "LCK"),
                            ("LCS", "LCS"),
                            ("LTA", "LTA"),
                            ("PCS", "PCS"),
                            ("VCS", "VCS"),
                            ("CBLOL", "CBLOL"),
                            ("OTHER", "Altro"),
                        ],
                        default="LEC",
                        max_length=20,
                    ),
                ),
                (
                    "leaguepedia_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "pandascore_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "db_table": "pro_teams",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ProPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=60)),
                ("nome_reale", models.CharField(blank=True, max_length=120, null=True)),
                ("nazionalita", models.CharField(blank=True, max_length=60, null=True)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ruolo",
                    models.CharField(
                        choices=[
                            ("TOP", "TOP"),
                            ("JUNGLE", "JUNGLE"),
                            ("MID", "MID"),
                            ("ADC", "ADC"),
                            ("SUPPORT", "SUPPORT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quotazione", models.PositiveIntegerField()),
                (
                    "competition",
                    models.CharField(
                        choices=[
                            ("LEC", "LEC"),
                            ("LPL", "LPL"),
                            ("LCK", "LCK"),
                            ("LCS", "LCS"),
                            ("LTA", "LTA"),
                            ("PCS", "PCS"),
                            ("VCS", "VCS"),
                            ("CBLOL", "CBLOL"),
                            ("OTHER", "Altro"),
                        ],
                        default="LEC",
                        max_length=20,
                    ),
                ),
                (
                    "leaguepedia_link",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, null=True
                    ),
                ),
                (
                    "pandascore_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("is_worlds_eligible", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giocatori",
                        to="teams.proteam",
                    ),
                ),
            ],
            options={
                "db_table": "pro_players",
                "ordering": ["nickname"],
                "indexes": [
                    models.Index(
                        fields=["competition", "ruolo"],
                        name="pro_players_competi_600b1f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nickname", "team"), name="uq_player_nickname_team"
                    )
                ],
            },
        ),
    ]
