# Generated by Django 5.1.15 on 2026-09-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineupPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TOP", "TOP"),
                            ("JUNGLE", "JUNGLE"),
                            ("MID", "MID"),
                            ("ADC", "ADC"),
                            ("SUPPORT", "SUPPORT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("USER", "USER"),
                            ("BACKFILL", "BACKFILL"),
                            ("AUTOMATIC", "AUTOMATIC"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fanta_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_periods",
                        to="leagues.fantateam",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_periods",
                        to="teams.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "lineup_periods",
                "ordering": ["fanta_team_id", "role", "valid_from"],
                "indexes": [
                    models.Index(
                        fields=["fanta_team", "role", "valid_from"],
                        name="lineup_peri_fanta_t_750b53_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fanta_team", "role", "valid_from"),
                        name="uq_lineup_period_slot",
                    )
                ],
            },
        ),
    ]
