# Generated by Django 5.1.15 on 2026-09-17 15:28

import django.db.models.deletion
import leagues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "codice_invito",
                    models.CharField(
                        default=leagues.models.generate_invite_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("crediti_iniziali", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("auction_open", models.BooleanField(default=False)),
                (
                    "participant_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "competition",
                    models.CharField(
                        choices=[
                            ("LEC", "LEC"),
                            ("LPL", "LPL"),
                            ("LCK", "LCK"),
                            ("LCS", "LCS"),
                            ("LTA", "LTA"),
                            ("PCS", "PCS"),
                            ("VCS", "VCS"),
                            ("CBLOL", "CBLOL"),
                            ("OTHER", "Altro"),
                        ],
                        default="LEC",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SETUP", "SETUP"),
                            ("AUCTION_OPEN", "AUCTION_OPEN"),
                            ("AUCTION_CLOSED", "AUCTION_CLOSED"),
                            ("RUNNING", "RUNNING"),
                            ("CLOSED", "CLOSED"),
                        ],
                        default="SETUP",
                        max_length=20,
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leghe_amministrate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leagues",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FantaTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("crediti_residui", models.IntegerField()),
                ("punti", models.FloatField(default=0.0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fanta_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fanta_teams",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "db_table": "fanta_teams",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AuctionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_bid", models.PositiveIntegerField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("WON", "WON"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to="teams.proplayer",
                    ),
                ),
                (
                    "highest_bidder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auctions_won",
                        to="leagues.fantateam",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "db_table": "auction_sessions",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crediti_spesi", models.PositiveIntegerField()),
                ("data_acquisto", models.DateTimeField(auto_now_add=True)),
                (
                    "fanta_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosa",
                        to="leagues.fantateam",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="teams.proplayer",
                    ),
                ),
            ],
            options={
                "db_table": "roster_entries",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="fantateam",
            constraint=models.UniqueConstraint(
                fields=("league", "owner"), name="uq_fantateam_league_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionsession",
            index=models.Index(
                fields=["status", "ends_at"], name="auction_ses_status_71bcb2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterentry",
            constraint=models.UniqueConstraint(
                fields=("fanta_team", "player"), name="uq_roster_team_player"
            ),
        ),
    ]
